### ISSUE TITLE
Rerender is called when component is destroyed

### ISSUE THREAD

**Issue by zcharli** [adopted-ember-addons/ember-collection#138]
**The Error:** You can't call rerender on a view being destroyed
**The Use Case:** Having a service that's receiving a stream of data, collected into an array. This array is binded to ember-collection. When we destroy the component, ie. navigate to another route, the observer of ember-collection still catches changed made from the data stream (WS). It tries to rerender when the component is dead. 

I hope someone could tell me that I'm doing something wrong and it's not the library. I patched mine up like so on `ember-collection.js`.

```
// ember-collection.js
_needsRevalidate(){
    if (this.isDestroyed || this.isDestroying) {return;}
    if (this._isGlimmer2()) {
      this.rerender();
    } else {
      needsRevalidate(this);
    }
  }
```

Using Ember 2.10.x

**Comment by rwwagner90** [comment]
@lukemelia is there a reason we would not want to put the `if (this.isDestroyed || this.isDestroying) {return;}` check in the official library?
