### ISSUE TITLE
Ember global deprecation violation, transitive dependency on ember-cli-babel@6

### ISSUE THREAD

**Issue by 22a** [adopted-ember-addons/ember-collection#221]
This addon has a transitive dependency on a version of `ember-cli-babel` below `7.26.6` via the `layout-bin-packer` addon: 

https://github.com/adopted-ember-addons/ember-collection/blob/279a75527c06997e2dcff8803da76290b9df6b9a/package.json#L28

https://github.com/adopted-ember-addons/ember-collection/blob/279a75527c06997e2dcff8803da76290b9df6b9a/yarn.lock#L9004-L9009
This causes the [ember global deprecation](https://deprecations.emberjs.com/v3.x/#toc_ember-global) warning to throw.

---

I've [opened a PR to upgrade `layout-bin-packer`'s `ember-cli-babel` version](https://github.com/stefanpenner/layout-bin-packer/pull/33) but I'm not yet certain this is the correct approach nor how this package can be released / who has access. I'll reach out in discord.

In the meantime, I'm opening **THIS** issue to track the progress towards getting that resolved and upsteamed here.

---

<details><summary>Details of the <strong>not-recommended, temporary</strong> workaround I'm using to unblock us for now</summary>
<p>

I've forked the repo to my employer's corporate GitHub account and [tagged a commit](https://github.com/intercom/layout-bin-packer/releases/tag/v2.0.0-ember.cli.babel.7.fork) that removed the `dist` dir from the packages `.gitignore` so the above PR can be used
```
  "resolutions": {
    "layout-bin-packer": "intercom/layout-bin-packer#v2.0.0-ember.cli.babel.7.fork"
  },
```

</p>
</details>

**Comment by hexadecy** [comment]
Fixed in ember-collection 3.0.0
it use:
```
layout-bin-packer "^2.0.0"
```
